version: '3.8'

services:
  redis-leader:
    image: redis:7
    container_name: redis-leader
    networks:
      - redis-net
    ports:
      - "6379:6379"

  redis-replica:
    image: redis:7
    container_name: redis-replica
    depends_on:
      - redis-leader
    command: >
      redis-server --replicaof redis-leader 6379
    networks:
      - redis-net
    ports:
      - "6380:6379"

networks:
  redis-net:
    driver: bridge
